// IStopWatchService.idl

// Declare any non-default types here with sequenceable or interface statements
interface xwg.harmony.stopwatch.StopWatchAgent {
    /*
     * Example of a service method that uses some parameters
     */
    void setCurrentTab([in] int index);
    int getCurrentTab();
    boolean start();
    void stop();
    boolean isRunning();
    long getStartTime();
    long getTime();
    void resetTime();
    void recordTime();
    String[] getLapTimes();
    void registerLocationEvent();
    double[] getCurrentLocation();
    double[] getTrailData();
}
